// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.2
// source: protos/objects/service.proto

package object

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ObjectRequest) Reset() {
	*x = ObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_objects_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRequest) ProtoMessage() {}

func (x *ObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_objects_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRequest.ProtoReflect.Descriptor instead.
func (*ObjectRequest) Descriptor() ([]byte, []int) {
	return file_protos_objects_service_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object *LargeObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *ObjectResponse) Reset() {
	*x = ObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_objects_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectResponse) ProtoMessage() {}

func (x *ObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_objects_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectResponse.ProtoReflect.Descriptor instead.
func (*ObjectResponse) Descriptor() ([]byte, []int) {
	return file_protos_objects_service_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectResponse) GetObject() *LargeObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type LargeObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *LargeObjectRequest) Reset() {
	*x = LargeObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_objects_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeObjectRequest) ProtoMessage() {}

func (x *LargeObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_objects_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeObjectRequest.ProtoReflect.Descriptor instead.
func (*LargeObjectRequest) Descriptor() ([]byte, []int) {
	return file_protos_objects_service_proto_rawDescGZIP(), []int{2}
}

func (x *LargeObjectRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LargeObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LargeObjects []*LargeObject `protobuf:"bytes,1,rep,name=largeObjects,proto3" json:"largeObjects,omitempty"`
}

func (x *LargeObjectResponse) Reset() {
	*x = LargeObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_objects_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeObjectResponse) ProtoMessage() {}

func (x *LargeObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_objects_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeObjectResponse.ProtoReflect.Descriptor instead.
func (*LargeObjectResponse) Descriptor() ([]byte, []int) {
	return file_protos_objects_service_proto_rawDescGZIP(), []int{3}
}

func (x *LargeObjectResponse) GetLargeObjects() []*LargeObject {
	if x != nil {
		return x.LargeObjects
	}
	return nil
}

type LargeObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XId           string     `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Index         uint32     `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Guid          string     `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	IsActive      bool       `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Balance       string     `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Picture       string     `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	Age           uint32     `protobuf:"varint,7,opt,name=age,proto3" json:"age,omitempty"`
	EyeColor      string     `protobuf:"bytes,8,opt,name=eyeColor,proto3" json:"eyeColor,omitempty"`
	Name          string     `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string     `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	Company       string     `protobuf:"bytes,11,opt,name=company,proto3" json:"company,omitempty"`
	Email         string     `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string     `protobuf:"bytes,13,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string     `protobuf:"bytes,14,opt,name=address,proto3" json:"address,omitempty"`
	About         string     `protobuf:"bytes,15,opt,name=about,proto3" json:"about,omitempty"`
	Registered    string     `protobuf:"bytes,16,opt,name=registered,proto3" json:"registered,omitempty"`
	Latitude      float64    `protobuf:"fixed64,17,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64    `protobuf:"fixed64,18,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Tags          []string   `protobuf:"bytes,19,rep,name=tags,proto3" json:"tags,omitempty"`
	Friends       []*Friends `protobuf:"bytes,20,rep,name=friends,proto3" json:"friends,omitempty"`
	Greeting      string     `protobuf:"bytes,21,opt,name=greeting,proto3" json:"greeting,omitempty"`
	FavoriteFruit string     `protobuf:"bytes,22,opt,name=favoriteFruit,proto3" json:"favoriteFruit,omitempty"`
}

func (x *LargeObject) Reset() {
	*x = LargeObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_objects_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LargeObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeObject) ProtoMessage() {}

func (x *LargeObject) ProtoReflect() protoreflect.Message {
	mi := &file_protos_objects_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeObject.ProtoReflect.Descriptor instead.
func (*LargeObject) Descriptor() ([]byte, []int) {
	return file_protos_objects_service_proto_rawDescGZIP(), []int{4}
}

func (x *LargeObject) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *LargeObject) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LargeObject) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *LargeObject) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *LargeObject) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *LargeObject) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *LargeObject) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *LargeObject) GetEyeColor() string {
	if x != nil {
		return x.EyeColor
	}
	return ""
}

func (x *LargeObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LargeObject) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *LargeObject) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *LargeObject) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LargeObject) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LargeObject) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LargeObject) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *LargeObject) GetRegistered() string {
	if x != nil {
		return x.Registered
	}
	return ""
}

func (x *LargeObject) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LargeObject) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LargeObject) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LargeObject) GetFriends() []*Friends {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *LargeObject) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

func (x *LargeObject) GetFavoriteFruit() string {
	if x != nil {
		return x.FavoriteFruit
	}
	return ""
}

type Friends struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Friends) Reset() {
	*x = Friends{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_objects_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friends) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friends) ProtoMessage() {}

func (x *Friends) ProtoReflect() protoreflect.Message {
	mi := &file_protos_objects_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friends.ProtoReflect.Descriptor instead.
func (*Friends) Descriptor() ([]byte, []int) {
	return file_protos_objects_service_proto_rawDescGZIP(), []int{5}
}

func (x *Friends) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friends) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protos_objects_service_proto protoreflect.FileDescriptor

var file_protos_objects_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x72, 0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x25, 0x0a, 0x0d, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x41, 0x0a, 0x0e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x2e, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x52, 0x0a, 0x13, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x6c, 0x61, 0x72, 0x67, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4c, 0x61, 0x72, 0x67, 0x65,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0c, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x22, 0xc7, 0x04, 0x0a, 0x0b, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x0f, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x67,
	0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x79, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x62, 0x6f,
	0x75, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x18, 0x13, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x2d, 0x0a,
	0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x52, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x46, 0x72, 0x75, 0x69, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x46, 0x72, 0x75, 0x69, 0x74, 0x22, 0x2d,
	0x0a, 0x07, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xaa, 0x01,
	0x0a, 0x0d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x53, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x1e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4c,
	0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4c,
	0x61, 0x72, 0x67, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x72, 0x70,
	0x63, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_objects_service_proto_rawDescOnce sync.Once
	file_protos_objects_service_proto_rawDescData = file_protos_objects_service_proto_rawDesc
)

func file_protos_objects_service_proto_rawDescGZIP() []byte {
	file_protos_objects_service_proto_rawDescOnce.Do(func() {
		file_protos_objects_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_objects_service_proto_rawDescData)
	})
	return file_protos_objects_service_proto_rawDescData
}

var file_protos_objects_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_objects_service_proto_goTypes = []interface{}{
	(*ObjectRequest)(nil),       // 0: rpc.object.ObjectRequest
	(*ObjectResponse)(nil),      // 1: rpc.object.ObjectResponse
	(*LargeObjectRequest)(nil),  // 2: rpc.object.LargeObjectRequest
	(*LargeObjectResponse)(nil), // 3: rpc.object.LargeObjectResponse
	(*LargeObject)(nil),         // 4: rpc.object.LargeObject
	(*Friends)(nil),             // 5: rpc.object.Friends
}
var file_protos_objects_service_proto_depIdxs = []int32{
	4, // 0: rpc.object.ObjectResponse.object:type_name -> rpc.object.LargeObject
	4, // 1: rpc.object.LargeObjectResponse.largeObjects:type_name -> rpc.object.LargeObject
	5, // 2: rpc.object.LargeObject.friends:type_name -> rpc.object.Friends
	2, // 3: rpc.object.ObjectService.GetLargeObject:input_type -> rpc.object.LargeObjectRequest
	0, // 4: rpc.object.ObjectService.GetObject:input_type -> rpc.object.ObjectRequest
	3, // 5: rpc.object.ObjectService.GetLargeObject:output_type -> rpc.object.LargeObjectResponse
	1, // 6: rpc.object.ObjectService.GetObject:output_type -> rpc.object.ObjectResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_objects_service_proto_init() }
func file_protos_objects_service_proto_init() {
	if File_protos_objects_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_objects_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_objects_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_objects_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LargeObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_objects_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LargeObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_objects_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LargeObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_objects_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friends); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_objects_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_objects_service_proto_goTypes,
		DependencyIndexes: file_protos_objects_service_proto_depIdxs,
		MessageInfos:      file_protos_objects_service_proto_msgTypes,
	}.Build()
	File_protos_objects_service_proto = out.File
	file_protos_objects_service_proto_rawDesc = nil
	file_protos_objects_service_proto_goTypes = nil
	file_protos_objects_service_proto_depIdxs = nil
}
